name: "yolov11"
backend: "python"

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 1, 84, 8400 ]
  }
]

# Configure instance group
instance_group: [
  { kind: KIND_MODEL, count: 2 }
]

max_batch_size: 1