name: "yolov11"
backend: "python"

input [
  {
    name: "INPUT__0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

# Configure instance group
instance_group: [
  { kind: KIND_MODEL, count: 2 }
]

# Disable batching for variable-length JPEG byte input
max_batch_size: 0

model_transaction_policy {
  decoupled: True
}
