name: "preprocessor"
backend: "python"

input [
  {
    name: "IMAGE_BYTES"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

output [
  {
    name: "PREPROCESSED_IMAGE"
    data_type: TYPE_FP32
    dims: [ 3, 800, 800 ]
  }
]

instance_group: [
  { kind: KIND_CPU, count: 2 }
]

max_batch_size: 1

