name: "preprocessor"
backend: "python"

input [
  {
    name: "IMAGE_BYTES"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "PREPROCESSED_IMAGE"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]

instance_group: [
  { kind: KIND_CPU, count: 8 }
]

max_batch_size: 1